; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Sun Dec 26 2021 18:18:31 GMT+0100 (Central European Standard Time)

