; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Sun Dec 26 2021 18:18:31 GMT+0100 (Central European Standard Time)
; Wait for set temperatures to be reached
M116 P0

