; homez.g
; called to home the Z axis
;
; Z high end homing

; generated by RepRapFirmware Configuration Tool v3.3.0 on Mon Aug 09 2021 16:24:35 GMT+0100 (British Summer Time)
G91              ; relative positioning
;G1 H2 Z30 F6000   ; lift Z relative to current position
G1 H1 Z167 F1800	; move Z up until the endstop is triggered 
G92 Z129.94         ; set Z position to axis maximum (you may want to adjust this)
G90
G1 Z117.4 F1500