; homevg
; called to home the V axis
;
; V high end homing

; generated by RepRapFirmware Configuration Tool v3.3.0 on Mon Aug 09 2021 16:24:35 GMT+0100 (British Summer Time)
G91              ; relative positioning
G1 H1 C0 F6000   ; lift V relative to current position
G1 H1 C60 F1800 ; move V up until the endstop is triggered
G92 C0         ; set V position to axis maximum (you may want to adjust this)